### GET request to example server
POST http://localhost:42069/
Content-Type: application/json

{
  "username": "asd"
}


###
GET http://localhost:42069/products
Accept: application/json
Authorization: w4fasdfa4g25g4
Authorization: w4fasdfg45gw4
Authorization: w4fasdgf543aw4
